### PR TITLE
Refresh workshop

### PR DESCRIPTION
**Pull request by EngAyoosh**
As discussed [here](https://github.com/foundersandcoders/master-reference/issues/631) I proposed the following changes : 
- Fix typos.
- adding links to keyword section
- adding more illustration for some points to be more clear.

### CODE REVIEW

**Comment by eliascodes** [comment]
@EngAyoosh why did you fork the node-girls workshop and make this PR here instead of addressing the comments made on [your original PR](https://github.com/node-girls/node-workshop/pull/46)?

**Comment by claireinez** [comment]
Nice catch @eliascodes, I hadn't seen this PR too, only the one on the Node Girls repo. @EngAyoosh I think it might be best if you address the changes requested on the Node Girls PR and then update this repo from the fork when the PR is merged?

**Comment by EngAyoosh** [comment]
Hi @eliascodes & @claireinez 
@mantagen tell me that I have to fork the node-girls workshop, because I don't have an access on the node-girls

**Comment by mantagen** [comment]
@eliascodes @claireinez @EngAyoosh my understanding for how this would work best (considering various reviewers and permissions) would be to:

1. fork the repo
2. make the changes on a branch on fork
3. create PR from fork/changes to fork/master
4. have them reviewed on the fork by the relevant curriculum planning parties
5. PR the reviewed changes from fork/master to original/master

(I think that was my advice @EngAyoosh ?)

**Comment by eliascodes** [comment]
@mantagen @EngAyoosh Oh I see. That's quite a few steps though, we can just make a PR directly from fork/changes to original/master (which we already have [here](https://github.com/node-girls/node-workshop/pull/46) right?). Then after it's merged we can either delete the fork or pull upstream changes on master.

Basically I think we can address @claireinez comments on the `refresh-workshop` branch in this fork, then push it, that should update the PR in the original and we can have it merged, no?

**Comment by mantagen** [comment]
Sure that's fine by me. Steps, many, yes; maybe too many.

**Comment by EngAyoosh** [comment]
@mantagen  yes exactly !
@eliascodes  & @mantagen  now ! should i make the requested changes the push it to the refresh-workshop branch in this fork repo ?

**Comment by eliascodes** [comment]
@EngAyoosh yes please

**Comment by claireinez** [comment]
Okay the PR to https://github.com/node-girls/node-workshop/pull/46 was merged. So the fork can be updated?

**Comment by eliascodes** [comment]
@claireinez Not sure we need this fork anymore tbh; master-reference links to the original node-girls repo. I think I'll just delete it.

@EngAyoosh thank you for your changes!

**Comment by claireinez** [comment]
Thanks @eliascodes!

**Pull request closed without merging**
